import { PostRenderHook } from "../config-types";

const markAsGenerated: PostRenderHook = (path, lines): string[] => {
  if (path.endsWith(".ts")) {
    return [
      "// @generated",
      "// This file is automatically generated by Kanel. Do not modify manually.",
      "",
      ...lines,
      "",
    ];
  }

  return lines;
};

export default markAsGenerated;
