import { PostRenderHookV3 } from "../config-types";

const markAsGenerated: PostRenderHookV3 = (
  path,
  lines,
  _instantiatedConfig,
): string[] => {
  const extension = path.split(".").pop();
  if (["ts", "tsx", "js", "jsx"].includes(extension)) {
    return [
      "// @generated",
      "// This file is automatically generated by Kanel. Do not modify manually.",
      "",
      ...lines,
      "",
    ];
  }
  if (["md"].includes(extension)) {
    return [
      "<!-- @generated",
      "This file is automatically generated by Kanel. Do not modify manually.",
      "-->",
      ...lines,
    ];
  }
  return lines;
};

export default markAsGenerated;
