// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as PublicSchema } from './public/PublicSchema';

type Database = PublicSchema;

export default Database;
