// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface get_customer_balance_params {
  p_customer_id: number;

  p_effective_date: Date;
}

/** Return type for get_customer_balance */
export type get_customer_balance_return_type = string;
