// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface inventory_held_by_customer_params {
  p_inventory_id: number;
}

/** Return type for inventory_held_by_customer */
export type inventory_held_by_customer_return_type = number;
