// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface last_day_params {
  $1: Date;
}

/** Return type for last_day */
export type last_day_return_type = Date;
