// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface rewards_report_params {
  min_monthly_purchases: number;

  min_dollar_amount_purchased: string;
}
