// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CityId } from './City';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type AddressId = number;

/** Represents the table public.address */
export default interface AddressTable {
  address_id: ColumnType<AddressId, AddressId | null, AddressId | null>;

  address: ColumnType<string, string, string | null>;

  address2: ColumnType<string | null, string | null, string | null>;

  district: ColumnType<string, string, string | null>;

  city_id: ColumnType<CityId, CityId, CityId | null>;

  postal_code: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string, string, string | null>;

  last_update: ColumnType<Date, Date | string | null, Date | string | null>;
}

export type Address = Selectable<AddressTable>;

export type NewAddress = Insertable<AddressTable>;

export type AddressUpdate = Updateable<AddressTable>;
