// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type CategoryId = number;

/** Represents the table public.category */
export default interface CategoryTable {
  category_id: ColumnType<CategoryId, CategoryId | null, CategoryId | null>;

  name: ColumnType<string, string, string | null>;

  last_update: ColumnType<Date, Date | string | null, Date | string | null>;
}

export type Category = Selectable<CategoryTable>;

export type NewCategory = Insertable<CategoryTable>;

export type CategoryUpdate = Updateable<CategoryTable>;
