// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CountryId } from './Country';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type CityId = number;

/** Represents the table public.city */
export default interface CityTable {
  city_id: ColumnType<CityId, CityId | null, CityId>;

  city: ColumnType<string, string, string>;

  country_id: ColumnType<CountryId, CountryId, CountryId>;

  last_update: ColumnType<Date, Date | string | null, Date | string>;
}

export type City = Selectable<CityTable>;

export type NewCity = Insertable<CityTable>;

export type CityUpdate = Updateable<CityTable>;
