// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CountryId } from './Country';
import type { ColumnType } from 'kysely';

export type CityId = number;

/** Represents the table public.city */
export default interface CityTable {
  city_id: ColumnType<CityId, CityId | null, CityId | null>;

  city: ColumnType<string, string, string | null>;

  country_id: ColumnType<CountryId, CountryId, CountryId | null>;

  last_update: ColumnType<Date | string, Date | string | null, Date | string | null>;
}

export type City = CityTable;
