// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AddressId } from './Address';
import type { ColumnType } from 'kysely';

export type CustomerId = number;

/** Represents the table public.customer */
export default interface CustomerTable {
  customer_id: ColumnType<CustomerId, CustomerId | null, CustomerId | null>;

  store_id: ColumnType<number, number, number | null>;

  first_name: ColumnType<string, string, string | null>;

  last_name: ColumnType<string, string, string | null>;

  email: ColumnType<string | null, string | null, string | null>;

  address_id: ColumnType<AddressId, AddressId, AddressId | null>;

  activebool: ColumnType<boolean, boolean | null, boolean | null>;

  create_date: ColumnType<Date | string, Date | string | null, Date | string | null>;

  last_update: ColumnType<Date | string | null, Date | string | null, Date | string | null>;

  active: ColumnType<number | null, number | null, number | null>;
}

export type Customer = CustomerTable;
