// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActorId } from './Actor';
import type { FilmId } from './Film';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.film_actor */
export default interface FilmActorTable {
  actor_id: ColumnType<ActorId, ActorId, ActorId | null>;

  film_id: ColumnType<FilmId, FilmId, FilmId | null>;

  last_update: ColumnType<Date, Date | string | null, Date | string | null>;
}

export type FilmActor = Selectable<FilmActorTable>;

export type NewFilmActor = Insertable<FilmActorTable>;

export type FilmActorUpdate = Updateable<FilmActorTable>;
