// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FilmId } from './Film';
import type MpaaRating from './MpaaRating';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the view public.film_list */
export default interface FilmListTable {
  fid: ColumnType<FilmId, never, never>;

  title: ColumnType<string, never, never>;

  description: ColumnType<string | null, never, never>;

  category: ColumnType<string, never, never>;

  price: ColumnType<string, never, never>;

  length: ColumnType<number | null, never, never>;

  rating: ColumnType<MpaaRating | null, never, never>;

  actors: ColumnType<string, never, never>;
}

export type FilmList = Selectable<FilmListTable>;
