// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FilmId } from './Film';
import type { CategoryId } from './Category';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.film_category */
export default interface FilmCategoryTable {
  film_id: ColumnType<FilmId, FilmId, FilmId>;

  category_id: ColumnType<CategoryId, CategoryId, CategoryId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type FilmCategory = Selectable<FilmCategoryTable>;

export type NewFilmCategory = Insertable<FilmCategoryTable>;

export type FilmCategoryUpdate = Updateable<FilmCategoryTable>;
