// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type Year from './Year';
import type { LanguageId } from './Language';
import type MpaaRating from './MpaaRating';
import type { ColumnType } from 'kysely';

export type FilmId = number;

/** Represents the table public.film */
export default interface FilmTable {
  film_id: ColumnType<FilmId, FilmId | null, FilmId | null>;

  title: ColumnType<string, string, string | null>;

  description: ColumnType<string | null, string | null, string | null>;

  release_year: ColumnType<Year | null, Year | null, Year | null>;

  language_id: ColumnType<LanguageId, LanguageId, LanguageId | null>;

  rental_duration: ColumnType<number, number | null, number | null>;

  rental_rate: ColumnType<string, string | null, string | null>;

  length: ColumnType<number | null, number | null, number | null>;

  replacement_cost: ColumnType<string, string | null, string | null>;

  rating: ColumnType<MpaaRating | null, MpaaRating | null, MpaaRating | null>;

  last_update: ColumnType<Date | string, Date | string | null, Date | string | null>;

  special_features: ColumnType<string[] | null, string[] | null, string[] | null>;

  fulltext: ColumnType<Set<string>, Set<string>, Set<string> | null>;
}

export type Film = FilmTable;
