// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type Year from './Year';
import type { LanguageId } from './Language';
import type MpaaRating from './MpaaRating';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type FilmId = number;

/** Represents the table public.film */
export default interface FilmTable {
  film_id: ColumnType<FilmId, FilmId | undefined, FilmId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  release_year: ColumnType<Year | null, Year | null, Year | null>;

  language_id: ColumnType<LanguageId, LanguageId, LanguageId>;

  rental_duration: ColumnType<number, number | undefined, number>;

  rental_rate: ColumnType<string, string | undefined, string>;

  length: ColumnType<number | null, number | null, number | null>;

  replacement_cost: ColumnType<string, string | undefined, string>;

  rating: ColumnType<MpaaRating | null, MpaaRating | null, MpaaRating | null>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;

  special_features: ColumnType<string[] | null, string[] | null, string[] | null>;

  fulltext: ColumnType<Set<string>, Set<string>, Set<string>>;
}

export type Film = Selectable<FilmTable>;

export type NewFilm = Insertable<FilmTable>;

export type FilmUpdate = Updateable<FilmTable>;
