// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CustomerId } from './Customer';
import type { StaffId } from './Staff';
import type { RentalId } from './Rental';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type PaymentId = number;

/** Represents the table public.payment */
export default interface PaymentTable {
  payment_id: ColumnType<PaymentId, PaymentId | undefined, PaymentId>;

  customer_id: ColumnType<CustomerId, CustomerId, CustomerId>;

  staff_id: ColumnType<StaffId, StaffId, StaffId>;

  rental_id: ColumnType<RentalId, RentalId, RentalId>;

  amount: ColumnType<string, string, string>;

  payment_date: ColumnType<Date, Date | string, Date | string>;
}

export type Payment = Selectable<PaymentTable>;

export type NewPayment = Insertable<PaymentTable>;

export type PaymentUpdate = Updateable<PaymentTable>;
