// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type CustomerTable from './Customer';
import type ActorTable from './Actor';
import type CategoryTable from './Category';
import type FilmTable from './Film';
import type FilmActorTable from './FilmActor';
import type FilmCategoryTable from './FilmCategory';
import type AddressTable from './Address';
import type CityTable from './City';
import type CountryTable from './Country';
import type InventoryTable from './Inventory';
import type LanguageTable from './Language';
import type PaymentTable from './Payment';
import type RentalTable from './Rental';
import type StaffTable from './Staff';
import type StoreTable from './Store';
import type OrdersTable from './Orders';
import type ActorInfoTable from './ActorInfo';
import type CustomerListTable from './CustomerList';
import type FilmListTable from './FilmList';
import type NicerButSlowerFilmListTable from './NicerButSlowerFilmList';
import type SalesByFilmCategoryTable from './SalesByFilmCategory';
import type SalesByStoreTable from './SalesByStore';
import type StaffListTable from './StaffList';

export default interface PublicSchema {
  customer: CustomerTable;

  actor: ActorTable;

  category: CategoryTable;

  film: FilmTable;

  film_actor: FilmActorTable;

  film_category: FilmCategoryTable;

  address: AddressTable;

  city: CityTable;

  country: CountryTable;

  inventory: InventoryTable;

  language: LanguageTable;

  payment: PaymentTable;

  rental: RentalTable;

  staff: StaffTable;

  store: StoreTable;

  orders: OrdersTable;

  actor_info: ActorInfoTable;

  customer_list: CustomerListTable;

  film_list: FilmListTable;

  nicer_but_slower_film_list: NicerButSlowerFilmListTable;

  sales_by_film_category: SalesByFilmCategoryTable;

  sales_by_store: SalesByStoreTable;

  staff_list: StaffListTable;
}
