// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { Customer } from './Customer';
import type { Actor } from './Actor';
import type { Category } from './Category';
import type { Film } from './Film';
import type { FilmActor } from './FilmActor';
import type { FilmCategory } from './FilmCategory';
import type { Address } from './Address';
import type { City } from './City';
import type { Country } from './Country';
import type { Inventory } from './Inventory';
import type { Language } from './Language';
import type { Payment } from './Payment';
import type { Rental } from './Rental';
import type { Staff } from './Staff';
import type { Store } from './Store';
import type { Orders } from './Orders';
import type { ActorInfo } from './ActorInfo';
import type { CustomerList } from './CustomerList';
import type { FilmList } from './FilmList';
import type { NicerButSlowerFilmList } from './NicerButSlowerFilmList';
import type { SalesByFilmCategory } from './SalesByFilmCategory';
import type { SalesByStore } from './SalesByStore';
import type { StaffList } from './StaffList';

export default interface PublicSchema {
  customer: Customer;

  actor: Actor;

  category: Category;

  film: Film;

  film_actor: FilmActor;

  film_category: FilmCategory;

  address: Address;

  city: City;

  country: Country;

  inventory: Inventory;

  language: Language;

  payment: Payment;

  rental: Rental;

  staff: Staff;

  store: Store;

  orders: Orders;

  actor_info: ActorInfo;

  customer_list: CustomerList;

  film_list: FilmList;

  nicer_but_slower_film_list: NicerButSlowerFilmList;

  sales_by_film_category: SalesByFilmCategory;

  sales_by_store: SalesByStore;

  staff_list: StaffList;
}
