// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType } from 'kysely';

/** Represents the view public.sales_by_store */
export default interface SalesByStoreTable {
  store: ColumnType<string, never, never>;

  manager: ColumnType<string, never, never>;

  total_sales: ColumnType<string, never, never>;
}

export type SalesByStore = SalesByStoreTable;
