// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AddressId } from './Address';
import bytea from 'bytea';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type StaffId = number;

/** Represents the table public.staff */
export default interface StaffTable {
  staff_id: ColumnType<StaffId, StaffId | undefined, StaffId>;

  first_name: ColumnType<string, string, string>;

  last_name: ColumnType<string, string, string>;

  address_id: ColumnType<AddressId, AddressId, AddressId>;

  email: ColumnType<string | null, string | null, string | null>;

  store_id: ColumnType<number, number, number>;

  active: ColumnType<boolean, boolean | undefined, boolean>;

  username: ColumnType<string, string, string>;

  password: ColumnType<string | null, string | null, string | null>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;

  picture: ColumnType<bytea | null, bytea | null, bytea | null>;
}

export type Staff = Selectable<StaffTable>;

export type NewStaff = Insertable<StaffTable>;

export type StaffUpdate = Updateable<StaffTable>;
