// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AddressId } from './Address';
import type { ColumnType } from 'kysely';

export type StaffId = number;

/** Represents the table public.staff */
export default interface StaffTable {
  staff_id: ColumnType<StaffId, StaffId | null, StaffId | null>;

  first_name: ColumnType<string, string, string | null>;

  last_name: ColumnType<string, string, string | null>;

  address_id: ColumnType<AddressId, AddressId, AddressId | null>;

  email: ColumnType<string | null, string | null, string | null>;

  store_id: ColumnType<number, number, number | null>;

  active: ColumnType<boolean, boolean | null, boolean | null>;

  username: ColumnType<string, string, string | null>;

  password: ColumnType<string | null, string | null, string | null>;

  last_update: ColumnType<Date | string, Date | string | null, Date | string | null>;

  picture: ColumnType<string | null, string | null, string | null>;
}

export type Staff = StaffTable;
