// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { StaffId } from './Staff';
import type { AddressId } from './Address';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type StoreId = number;

/** Represents the table public.store */
export default interface StoreTable {
  store_id: ColumnType<StoreId, StoreId | null, StoreId>;

  manager_staff_id: ColumnType<StaffId, StaffId, StaffId>;

  address_id: ColumnType<AddressId, AddressId, AddressId>;

  last_update: ColumnType<Date, Date | string | null, Date | string>;
}

export type Store = Selectable<StoreTable>;

export type NewStore = Insertable<StoreTable>;

export type StoreUpdate = Updateable<StoreTable>;
