// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface _group_concat_params {
  $1: string;

  $2: string;
}

/** Return type for _group_concat */
export type _group_concat_return_type = string;
