// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActorId } from './Actor';
import { z } from 'zod';

/** Represents the view public.actor_info */
export default interface ActorInfo {
  /** Database type: pg_catalog.int4 */
  actor_id: ActorId;

  /** Database type: pg_catalog.varchar */
  first_name: string;

  /** Database type: pg_catalog.varchar */
  last_name: string;

  /** Database type: pg_catalog.text */
  film_info: string;
}

/** Zod schema for actor_info */
export const actorInfo = z.object({
  actor_id: z.number(),
  first_name: z.string(),
  last_name: z.string(),
  film_info: z.string(),
});
