// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { ActorId } from './Actor';

/** Represents the view public.actor_info */
export default interface ActorInfo {
  actor_id: ActorId;

  first_name: string;

  last_name: string;

  film_info: string;
}
