// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { CityId } from './City';

/** Identifier type for address */
export type AddressId = number & { __flavor?: 'AddressId' };

/** Represents the table public.address */
export default interface Address {
  address_id: AddressId;

  address: string;

  address2: string | null;

  district: string;

  city_id: CityId;

  postal_code: string | null;

  phone: string;

  last_update: Date;
}

/** Represents the initializer for the table public.address */
export interface AddressInitializer {
  /** Default value: nextval('address_address_id_seq'::regclass) */
  address_id?: AddressId;

  address: string;

  address2?: string | null;

  district: string;

  city_id: CityId;

  postal_code?: string | null;

  phone: string;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.address */
export interface AddressMutator {
  address_id?: AddressId;

  address?: string;

  address2?: string | null;

  district?: string;

  city_id?: CityId;

  postal_code?: string | null;

  phone?: string;

  last_update?: Date;
}
