// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for category */
export type CategoryId = number & { __flavor?: 'CategoryId' };

/** Represents the table public.category */
export default interface Category {
  category_id: CategoryId;

  name: string;

  last_update: Date;
}

/** Represents the initializer for the table public.category */
export interface CategoryInitializer {
  /** Default value: nextval('category_category_id_seq'::regclass) */
  category_id?: CategoryId;

  name: string;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.category */
export interface CategoryMutator {
  category_id?: CategoryId;

  name?: string;

  last_update?: Date;
}
