// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { CustomerId } from './Customer';

/** Represents the view public.customer_list */
export default interface CustomerList {
  id: CustomerId;

  name: string;

  address: string;

  'zip code': string;

  phone: string;

  city: string;

  country: string;

  notes: string;

  sid: number;
}
