// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { FilmId } from './Film';
import { CategoryId } from './Category';

/** Represents the table public.film_category */
export default interface FilmCategory {
  film_id: FilmId;

  category_id: CategoryId;

  last_update: Date;
}

/** Represents the initializer for the table public.film_category */
export interface FilmCategoryInitializer {
  film_id: FilmId;

  category_id: CategoryId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.film_category */
export interface FilmCategoryMutator {
  film_id?: FilmId;

  category_id?: CategoryId;

  last_update?: Date;
}
