// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { FilmId } from './Film';
import MpaaRating from './MpaaRating';

/** Represents the view public.film_list */
export default interface FilmList {
  fid: FilmId;

  title: string;

  description: string;

  category: string;

  price: string;

  length: number;

  rating: MpaaRating;

  actors: string;
}
