// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { filmId, type FilmId } from './Film.js';
import { categoryId, type CategoryId } from './Category.js';
import { z } from 'zod';

/** Represents the table public.film_category */
export default interface FilmCategory {
  /** Database type: pg_catalog.int2 */
  film_id: FilmId;

  /** Database type: pg_catalog.int2 */
  category_id: CategoryId;

  /** Database type: pg_catalog.timestamp */
  last_update: Date;
}

/** Represents the initializer for the table public.film_category */
export interface FilmCategoryInitializer {
  /** Database type: pg_catalog.int2 */
  film_id: FilmId;

  /** Database type: pg_catalog.int2 */
  category_id: CategoryId;

  /**
   * Database type: pg_catalog.timestamp
   * Default value: now()
   */
  last_update?: Date;
}

/** Represents the mutator for the table public.film_category */
export interface FilmCategoryMutator {
  /** Database type: pg_catalog.int2 */
  film_id?: FilmId;

  /** Database type: pg_catalog.int2 */
  category_id?: CategoryId;

  /** Database type: pg_catalog.timestamp */
  last_update?: Date;
}

export const filmCategory = z.object({
  film_id: filmId,
  category_id: categoryId,
  last_update: z.date(),
}) as unknown as z.Schema<FilmCategory>;

export const filmCategoryInitializer = z.object({
  film_id: filmId,
  category_id: categoryId,
  last_update: z.date().optional(),
}) as unknown as z.Schema<FilmCategoryInitializer>;

export const filmCategoryMutator = z.object({
  film_id: filmId.optional(),
  category_id: categoryId.optional(),
  last_update: z.date().optional(),
}) as unknown as z.Schema<FilmCategoryMutator>;
