// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.mpaa_rating */
enum MpaaRating {
  G = 'G',
  PG = 'PG',
  'PG-13' = 'PG-13',
  R = 'R',
  'NC-17' = 'NC-17',
};

export default MpaaRating;
