// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface new_func_params {
  p_film_id: number;

  p_store_id: number;

  inventory_id: number;

  film_id: number;
}

/** Return type for new_func */
export interface new_func_return_type {
  inventory_id: number;

  film_id: number;
}
