// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { filmId, type FilmId } from './Film.js';
import { mpaaRating, type default as MpaaRating } from './MpaaRating.js';
import { z } from 'zod';

/** Represents the view public.nicer_but_slower_film_list */
export default interface NicerButSlowerFilmList {
  /** Database type: pg_catalog.int4 */
  fid: FilmId;

  /** Database type: pg_catalog.varchar */
  title: string;

  /** Database type: pg_catalog.text */
  description: string | null;

  /** Database type: pg_catalog.varchar */
  category: string;

  /** Database type: pg_catalog.numeric */
  price: string;

  /** Database type: pg_catalog.int2 */
  length: number | null;

  /** Database type: public.mpaa_rating */
  rating: MpaaRating | null;

  /** Database type: pg_catalog.text */
  actors: string;
}

export const nicerButSlowerFilmList = z.object({
  fid: filmId,
  title: z.string(),
  description: z.string().nullable(),
  category: z.string(),
  price: z.string(),
  length: z.number().nullable(),
  rating: mpaaRating.nullable(),
  actors: z.string(),
}) as unknown as z.Schema<NicerButSlowerFilmList>;
