// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { CustomerId } from './Customer';
import { StaffId } from './Staff';
import { RentalId } from './Rental';

/** Identifier type for payment */
export type PaymentId = number & { __flavor?: 'PaymentId' };

/** Represents the table public.payment */
export default interface Payment {
  payment_id: PaymentId;

  customer_id: CustomerId;

  staff_id: StaffId;

  rental_id: RentalId;

  amount: string;

  payment_date: Date;
}

/** Represents the initializer for the table public.payment */
export interface PaymentInitializer {
  /** Default value: nextval('payment_payment_id_seq'::regclass) */
  payment_id?: PaymentId;

  customer_id: CustomerId;

  staff_id: StaffId;

  rental_id: RentalId;

  amount: string;

  payment_date: Date;
}

/** Represents the mutator for the table public.payment */
export interface PaymentMutator {
  payment_id?: PaymentId;

  customer_id?: CustomerId;

  staff_id?: StaffId;

  rental_id?: RentalId;

  amount?: string;

  payment_date?: Date;
}
