// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { InventoryId } from './Inventory';
import { CustomerId } from './Customer';
import { StaffId } from './Staff';

/** Identifier type for rental */
export type RentalId = number & { __flavor?: 'RentalId' };

/** Represents the table public.rental */
export default interface Rental {
  rental_id: RentalId;

  rental_date: Date;

  inventory_id: InventoryId;

  customer_id: CustomerId;

  return_date: Date | null;

  staff_id: StaffId;

  last_update: Date;
}

/** Represents the initializer for the table public.rental */
export interface RentalInitializer {
  /** Default value: nextval('rental_rental_id_seq'::regclass) */
  rental_id?: RentalId;

  rental_date: Date;

  inventory_id: InventoryId;

  customer_id: CustomerId;

  return_date?: Date | null;

  staff_id: StaffId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.rental */
export interface RentalMutator {
  rental_id?: RentalId;

  rental_date?: Date;

  inventory_id?: InventoryId;

  customer_id?: CustomerId;

  return_date?: Date | null;

  staff_id?: StaffId;

  last_update?: Date;
}
