// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.sales_by_film_category */
export default interface SalesByFilmCategory {
  category: string;

  total_sales: string;
}
