// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.sales_by_film_category */
export default interface SalesByFilmCategory {
  /** Database type: pg_catalog.varchar */
  category: string;

  /** Database type: pg_catalog.numeric */
  total_sales: string;
}
