// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the view public.sales_by_store */
export default interface SalesByStore {
  /** Database type: pg_catalog.text */
  store: string;

  /** Database type: pg_catalog.text */
  manager: string;

  /** Database type: pg_catalog.numeric */
  total_sales: string;
}

export const salesByStore = z.object({
  store: z.string(),
  manager: z.string(),
  total_sales: z.string(),
}) as unknown as z.Schema<SalesByStore>;
