// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.sales_by_store */
export default interface SalesByStore {
  /** Database type: pg_catalog.text */
  store: string;

  /** Database type: pg_catalog.text */
  manager: string;

  /** Database type: pg_catalog.numeric */
  total_sales: string;
}
