// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view public.sales_by_store */
export default interface SalesByStore {
  store: string;

  manager: string;

  total_sales: string;
}
