// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { AddressId } from './Address';
import bytea from 'bytea';

/** Identifier type for staff */
export type StaffId = number & { __flavor?: 'StaffId' };

/** Represents the table public.staff */
export default interface Staff {
  staff_id: StaffId;

  first_name: string;

  last_name: string;

  address_id: AddressId;

  email: string | null;

  store_id: number;

  active: boolean;

  username: string;

  password: string | null;

  last_update: Date;

  picture: bytea | null;
}

/** Represents the initializer for the table public.staff */
export interface StaffInitializer {
  /** Default value: nextval('staff_staff_id_seq'::regclass) */
  staff_id?: StaffId;

  first_name: string;

  last_name: string;

  address_id: AddressId;

  email?: string | null;

  store_id: number;

  /** Default value: true */
  active?: boolean;

  username: string;

  password?: string | null;

  /** Default value: now() */
  last_update?: Date;

  picture?: bytea | null;
}

/** Represents the mutator for the table public.staff */
export interface StaffMutator {
  staff_id?: StaffId;

  first_name?: string;

  last_name?: string;

  address_id?: AddressId;

  email?: string | null;

  store_id?: number;

  active?: boolean;

  username?: string;

  password?: string | null;

  last_update?: Date;

  picture?: bytea | null;
}
