// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { StaffId } from './Staff';

/** Represents the view public.staff_list */
export default interface StaffList {
  id: StaffId;

  name: string;

  address: string;

  'zip code': string;

  phone: string;

  city: string;

  country: string;

  sid: number;
}
