// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { staffId, type StaffId } from './Staff.js';
import { addressId, type AddressId } from './Address.js';
import { z } from 'zod';

/** Identifier type for store */
export type StoreId = number & { __flavor?: 'StoreId' };

/** Represents the table public.store */
export default interface Store {
  /** Database type: pg_catalog.int4 */
  store_id: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id: AddressId;

  /** Database type: pg_catalog.timestamp */
  last_update: Date;
}

/** Represents the initializer for the table public.store */
export interface StoreInitializer {
  /**
   * Database type: pg_catalog.int4
   * Default value: nextval('store_store_id_seq'::regclass)
   */
  store_id?: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id: AddressId;

  /**
   * Database type: pg_catalog.timestamp
   * Default value: now()
   */
  last_update?: Date;
}

/** Represents the mutator for the table public.store */
export interface StoreMutator {
  /** Database type: pg_catalog.int4 */
  store_id?: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id?: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id?: AddressId;

  /** Database type: pg_catalog.timestamp */
  last_update?: Date;
}

export const storeId = z.number() as unknown as z.Schema<StoreId>;

export const store = z.object({
  store_id: storeId,
  manager_staff_id: staffId,
  address_id: addressId,
  last_update: z.date(),
}) as unknown as z.Schema<Store>;

export const storeInitializer = z.object({
  store_id: storeId.optional(),
  manager_staff_id: staffId,
  address_id: addressId,
  last_update: z.date().optional(),
}) as unknown as z.Schema<StoreInitializer>;

export const storeMutator = z.object({
  store_id: storeId.optional(),
  manager_staff_id: staffId.optional(),
  address_id: addressId.optional(),
  last_update: z.date().optional(),
}) as unknown as z.Schema<StoreMutator>;
