// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { staffId } from './Staff';
import type { StaffId } from './Staff';
import { addressId } from './Address';
import type { AddressId } from './Address';
import { z } from 'zod';

/** Identifier type for store */
export type StoreId = number & { __flavor?: 'StoreId' };

/** Represents the table public.store */
export default interface Store {
  /** Database type: pg_catalog.int4 */
  store_id: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id: AddressId;

  /** Database type: pg_catalog.timestamp */
  last_update: Date;
}

/** Represents the initializer for the table public.store */
export interface StoreInitializer {
  /**
   * Database type: pg_catalog.int4
   * Default value: nextval('store_store_id_seq'::regclass)
   */
  store_id?: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id: AddressId;

  /**
   * Database type: pg_catalog.timestamp
   * Default value: now()
   */
  last_update?: Date;
}

/** Represents the mutator for the table public.store */
export interface StoreMutator {
  /** Database type: pg_catalog.int4 */
  store_id?: StoreId;

  /** Database type: pg_catalog.int2 */
  manager_staff_id?: StaffId;

  /** Database type: pg_catalog.int2 */
  address_id?: AddressId;

  /** Database type: pg_catalog.timestamp */
  last_update?: Date;
}

export const storeId: z.Schema<StoreId> = z.number() as any;

export const store: z.Schema<Store> = z.object({
  store_id: storeId,
  manager_staff_id: staffId,
  address_id: addressId,
  last_update: z.date(),
}) as any;

export const storeInitializer: z.Schema<StoreInitializer> = z.object({
  store_id: storeId.optional(),
  manager_staff_id: staffId,
  address_id: addressId,
  last_update: z.date().optional(),
}) as any;

export const storeMutator: z.Schema<StoreMutator> = z.object({
  store_id: storeId.optional(),
  manager_staff_id: staffId.optional(),
  address_id: addressId.optional(),
  last_update: z.date().optional(),
}) as any;
