// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the domain public.year */
type Year = number;

export default Year;

/** Zod schema for year */
export const year = z.number();
