// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.actor */
export type ActorActorId = number & { __brand: 'public.actor' };

/** Represents the table public.actor */
export default interface ActorTable {
  actor_id: ColumnType<ActorActorId, ActorActorId | undefined, ActorActorId>;

  first_name: ColumnType<string, string, string>;

  last_name: ColumnType<string, string, string>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Actor = Selectable<ActorTable>;

export type NewActor = Insertable<ActorTable>;

export type ActorUpdate = Updateable<ActorTable>;
