// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActorActorId } from './Actor';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the view public.actor_info */
export default interface ActorInfoTable {
  actor_id: ColumnType<ActorActorId, never, never>;

  first_name: ColumnType<string, never, never>;

  last_name: ColumnType<string, never, never>;

  film_info: ColumnType<string, never, never>;
}

export type ActorInfo = Selectable<ActorInfoTable>;
