// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CityCityId } from './City';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.address */
export type AddressAddressId = number & { __brand: 'public.address' };

/** Represents the table public.address */
export default interface AddressTable {
  address_id: ColumnType<AddressAddressId, AddressAddressId | undefined, AddressAddressId>;

  address: ColumnType<string, string, string>;

  address2: ColumnType<string | null, string | null, string | null>;

  district: ColumnType<string, string, string>;

  city_id: ColumnType<CityCityId, CityCityId, CityCityId>;

  postal_code: ColumnType<string | null, string | null, string | null>;

  phone: ColumnType<string, string, string>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Address = Selectable<AddressTable>;

export type NewAddress = Insertable<AddressTable>;

export type AddressUpdate = Updateable<AddressTable>;
