// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.category */
export type CategoryCategoryId = number & { __brand: 'public.category' };

/** Represents the table public.category */
export default interface CategoryTable {
  category_id: ColumnType<CategoryCategoryId, CategoryCategoryId | undefined, CategoryCategoryId>;

  name: ColumnType<string, string, string>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Category = Selectable<CategoryTable>;

export type NewCategory = Insertable<CategoryTable>;

export type CategoryUpdate = Updateable<CategoryTable>;
