// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CountryCountryId } from './Country';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.city */
export type CityCityId = number & { __brand: 'public.city' };

/** Represents the table public.city */
export default interface CityTable {
  city_id: ColumnType<CityCityId, CityCityId | undefined, CityCityId>;

  city: ColumnType<string, string, string>;

  country_id: ColumnType<CountryCountryId, CountryCountryId, CountryCountryId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type City = Selectable<CityTable>;

export type NewCity = Insertable<CityTable>;

export type CityUpdate = Updateable<CityTable>;
