// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.country */
export type CountryCountryId = number & { __brand: 'public.country' };

/** Represents the table public.country */
export default interface CountryTable {
  country_id: ColumnType<CountryCountryId, CountryCountryId | undefined, CountryCountryId>;

  country: ColumnType<string, string, string>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Country = Selectable<CountryTable>;

export type NewCountry = Insertable<CountryTable>;

export type CountryUpdate = Updateable<CountryTable>;
