// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CustomerCustomerId } from './Customer';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the view public.customer_list */
export default interface CustomerListTable {
  id: ColumnType<CustomerCustomerId, never, never>;

  name: ColumnType<string, never, never>;

  address: ColumnType<string, never, never>;

  'zip code': ColumnType<string | null, never, never>;

  phone: ColumnType<string, never, never>;

  city: ColumnType<string, never, never>;

  country: ColumnType<string, never, never>;

  notes: ColumnType<string, never, never>;

  sid: ColumnType<number, never, never>;
}

export type CustomerList = Selectable<CustomerListTable>;
