// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActorActorId } from './Actor';
import type { FilmFilmId } from './Film';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.film_actor */
export default interface FilmActorTable {
  actor_id: ColumnType<ActorActorId, ActorActorId, ActorActorId>;

  film_id: ColumnType<FilmFilmId, FilmFilmId, FilmFilmId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type FilmActor = Selectable<FilmActorTable>;

export type NewFilmActor = Insertable<FilmActorTable>;

export type FilmActorUpdate = Updateable<FilmActorTable>;
