// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as Year } from './Year';
import type { LanguageLanguageId } from './Language';
import type { default as MpaaRating } from './MpaaRating';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.film */
export type FilmFilmId = number & { __brand: 'public.film' };

/** Represents the table public.film */
export default interface FilmTable {
  film_id: ColumnType<FilmFilmId, FilmFilmId | undefined, FilmFilmId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  release_year: ColumnType<Year | null, Year | null, Year | null>;

  language_id: ColumnType<LanguageLanguageId, LanguageLanguageId, LanguageLanguageId>;

  rental_duration: ColumnType<number, number | undefined, number>;

  rental_rate: ColumnType<string, string | undefined, string>;

  length: ColumnType<number | null, number | null, number | null>;

  replacement_cost: ColumnType<string, string | undefined, string>;

  rating: ColumnType<MpaaRating | null, MpaaRating | null, MpaaRating | null>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;

  special_features: ColumnType<string[] | null, string[] | null, string[] | null>;

  fulltext: ColumnType<unknown, unknown, unknown>;
}

export type Film = Selectable<FilmTable>;

export type NewFilm = Insertable<FilmTable>;

export type FilmUpdate = Updateable<FilmTable>;
