// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface film_not_in_stock_params {
  p_film_id: number;

  p_store_id: number;

  p_film_count: number;
}

/** Return type for film_not_in_stock */
export type film_not_in_stock_return_type = number;
