// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FilmFilmId } from './Film';
import type { CategoryCategoryId } from './Category';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.film_category */
export default interface FilmCategoryTable {
  film_id: ColumnType<FilmFilmId, FilmFilmId, FilmFilmId>;

  category_id: ColumnType<CategoryCategoryId, CategoryCategoryId, CategoryCategoryId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type FilmCategory = Selectable<FilmCategoryTable>;

export type NewFilmCategory = Insertable<FilmCategoryTable>;

export type FilmCategoryUpdate = Updateable<FilmCategoryTable>;
