// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FilmFilmId } from './Film';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.inventory */
export type InventoryInventoryId = number & { __brand: 'public.inventory' };

/** Represents the table public.inventory */
export default interface InventoryTable {
  inventory_id: ColumnType<InventoryInventoryId, InventoryInventoryId | undefined, InventoryInventoryId>;

  film_id: ColumnType<FilmFilmId, FilmFilmId, FilmFilmId>;

  store_id: ColumnType<number, number, number>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Inventory = Selectable<InventoryTable>;

export type NewInventory = Insertable<InventoryTable>;

export type InventoryUpdate = Updateable<InventoryTable>;
