// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface inventory_in_stock_params {
  p_inventory_id: number;
}

/** Return type for inventory_in_stock */
export type inventory_in_stock_return_type = boolean;
