// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.mpaa_rating */
type MpaaRating = 
  | 'G'
  | 'PG'
  | 'PG-13'
  | 'R'
  | 'NC-17';

export default MpaaRating;
