// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CustomerCustomerId } from './Customer';
import type { StaffStaffId } from './Staff';
import type { RentalRentalId } from './Rental';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.payment */
export type PaymentPaymentId = number & { __brand: 'public.payment' };

/** Represents the table public.payment */
export default interface PaymentTable {
  payment_id: ColumnType<PaymentPaymentId, PaymentPaymentId | undefined, PaymentPaymentId>;

  customer_id: ColumnType<CustomerCustomerId, CustomerCustomerId, CustomerCustomerId>;

  staff_id: ColumnType<StaffStaffId, StaffStaffId, StaffStaffId>;

  rental_id: ColumnType<RentalRentalId, RentalRentalId, RentalRentalId>;

  amount: ColumnType<string, string, string>;

  payment_date: ColumnType<Date, Date | string, Date | string>;
}

export type Payment = Selectable<PaymentTable>;

export type NewPayment = Insertable<PaymentTable>;

export type PaymentUpdate = Updateable<PaymentTable>;
