// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as LanguageTable } from './Language';
import type { default as FilmActorTable } from './FilmActor';
import type { default as ActorTable } from './Actor';
import type { default as FilmCategoryTable } from './FilmCategory';
import type { default as InventoryTable } from './Inventory';
import type { default as AddressTable } from './Address';
import type { default as RentalTable } from './Rental';
import type { default as CountryTable } from './Country';
import type { default as StaffTable } from './Staff';
import type { default as CustomerTable } from './Customer';
import type { default as StoreTable } from './Store';
import type { default as CategoryTable } from './Category';
import type { default as PaymentTable } from './Payment';
import type { default as FilmTable } from './Film';
import type { default as CityTable } from './City';
import type { default as StaffListTable } from './StaffList';
import type { default as ActorInfoTable } from './ActorInfo';
import type { default as FilmListTable } from './FilmList';
import type { default as SalesByFilmCategoryTable } from './SalesByFilmCategory';
import type { default as SalesByStoreTable } from './SalesByStore';
import type { default as CustomerListTable } from './CustomerList';
import type { default as NicerButSlowerFilmListTable } from './NicerButSlowerFilmList';

export default interface PublicSchema {
  language: LanguageTable;

  film_actor: FilmActorTable;

  actor: ActorTable;

  film_category: FilmCategoryTable;

  inventory: InventoryTable;

  address: AddressTable;

  rental: RentalTable;

  country: CountryTable;

  staff: StaffTable;

  customer: CustomerTable;

  store: StoreTable;

  category: CategoryTable;

  payment: PaymentTable;

  film: FilmTable;

  city: CityTable;

  staff_list: StaffListTable;

  actor_info: ActorInfoTable;

  film_list: FilmListTable;

  sales_by_film_category: SalesByFilmCategoryTable;

  sales_by_store: SalesByStoreTable;

  customer_list: CustomerListTable;

  nicer_but_slower_film_list: NicerButSlowerFilmListTable;
}
