// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { InventoryInventoryId } from './Inventory';
import type { CustomerCustomerId } from './Customer';
import type { StaffStaffId } from './Staff';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.rental */
export type RentalRentalId = number & { __brand: 'public.rental' };

/** Represents the table public.rental */
export default interface RentalTable {
  rental_id: ColumnType<RentalRentalId, RentalRentalId | undefined, RentalRentalId>;

  rental_date: ColumnType<Date, Date | string, Date | string>;

  inventory_id: ColumnType<InventoryInventoryId, InventoryInventoryId, InventoryInventoryId>;

  customer_id: ColumnType<CustomerCustomerId, CustomerCustomerId, CustomerCustomerId>;

  return_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  staff_id: ColumnType<StaffStaffId, StaffStaffId, StaffStaffId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Rental = Selectable<RentalTable>;

export type NewRental = Insertable<RentalTable>;

export type RentalUpdate = Updateable<RentalTable>;
