// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { StaffStaffId } from './Staff';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the view public.staff_list */
export default interface StaffListTable {
  id: ColumnType<StaffStaffId, never, never>;

  name: ColumnType<string, never, never>;

  address: ColumnType<string, never, never>;

  'zip code': ColumnType<string | null, never, never>;

  phone: ColumnType<string, never, never>;

  city: ColumnType<string, never, never>;

  country: ColumnType<string, never, never>;

  sid: ColumnType<number, never, never>;
}

export type StaffList = Selectable<StaffListTable>;
