// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AddressAddressId } from './Address';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.staff */
export type StaffStaffId = number & { __brand: 'public.staff' };

/** Represents the table public.staff */
export default interface StaffTable {
  staff_id: ColumnType<StaffStaffId, StaffStaffId | undefined, StaffStaffId>;

  first_name: ColumnType<string, string, string>;

  last_name: ColumnType<string, string, string>;

  address_id: ColumnType<AddressAddressId, AddressAddressId, AddressAddressId>;

  email: ColumnType<string | null, string | null, string | null>;

  store_id: ColumnType<number, number, number>;

  active: ColumnType<boolean, boolean | undefined, boolean>;

  username: ColumnType<string, string, string>;

  password: ColumnType<string | null, string | null, string | null>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;

  picture: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type Staff = Selectable<StaffTable>;

export type NewStaff = Insertable<StaffTable>;

export type StaffUpdate = Updateable<StaffTable>;
