// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { StaffStaffId } from './Staff';
import type { AddressAddressId } from './Address';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.store */
export type StoreStoreId = number & { __brand: 'public.store' };

/** Represents the table public.store */
export default interface StoreTable {
  store_id: ColumnType<StoreStoreId, StoreStoreId | undefined, StoreStoreId>;

  manager_staff_id: ColumnType<StaffStaffId, StaffStaffId, StaffStaffId>;

  address_id: ColumnType<AddressAddressId, AddressAddressId, AddressAddressId>;

  last_update: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Store = Selectable<StoreTable>;

export type NewStore = Insertable<StoreTable>;

export type StoreUpdate = Updateable<StoreTable>;
