// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type PublicSchema from './public/PublicSchema';

type Database = PublicSchema;

export default Database;
