// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table test.some_table */
export default interface SomeTable {
  id: number | null;
}

/** Represents the initializer for the table test.some_table */
export interface SomeTableInitializer {
  id?: number | null;
}

/** Represents the mutator for the table test.some_table */
export interface SomeTableMutator {
  id?: number | null;
}
